# This is a sample Python script.

# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.


#def print_hi(name):
    # Use a breakpoint in the code line below to debug your script.
   # print(f'Hi, {name}')  # Press Ctrl+F8 to toggle the breakpoint.


# Press the green button in the gutter to run the script.
#if __name__ == '__main__':
  #  print_hi('PyCharm')

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
from flask import Flask, render_template, request
app = Flask(__name__)

@app.route("/", methods = ['GET', 'POST'])
def hello():
  player_list = ['Precious Achiuwa',
'Steven Adams',
'Bam Adebayo',
'LaMarcus Aldridge',
'Ty-Shon Alexander',
'Nickeil Alexander-Walker',
'Grayson Allen',
'Jarrett Allen',
'Al-Farouq Aminu',

'Kyle Anderson',
'Giannis Antetokounmpo',

'Kostas Antetokounmpo',
'Thanasis Antetokounmpo',

'Carmelo Anthony',
'Cole Anthony',
'Ogugua Anunoby',

'Ryan Arcidiacono',
'Trevor Ariza',
'D.J. Augustin',
'Deni Avdija',
'Deandre Ayton',
'Udoka Azubuike',
'Dwayne Bacon',
'Marvin Bagley III',
'LaMelo Ball',
'Lonzo Ball',
'Mohamed Bamba',
'Desmond Bane',
'Harrison Barnes',
'R.J. Barrett',
'Will Barton',
'Keita Bates-Diop',
'Nicolas Batum',
'Aron Baynes',

'Kent Bazemore',
'Darius Bazley',
'Bradley Beal',
'Malik Beasley',
'DeAndre Bembry' ,
'Davis Bertans',
'Patrick Beverley',
'Saddiq Bey',
'Tyler Bey',
'Khem Birch',
'Goga Bitadze',
'Bismack Biyombo',
'Nemanja Bjelica',
'Eric Bledsoe',
'Keljin Blevins',
'Bogdan Bogdanovic',
'Bojan Bogdanovic',

'Bol Bol',
'Isaac Bonga',
'Devin Booker',
'Chris Boucher',

'Brian Bowen II',
'Avery Bradley',
'Tony Bradley',
'Jarrell Brantley',
'Ignas Brazdeikis',

'Mikal Bridges',
'Miles Bridges',
'Malcolm Brogdon',
'Dillon Brooks',
'Jaylen Brown',
'Bruce Brown, Jr. ',
'Troy Brown, Jr. ',
'Moses Brown',
'Sterling Brown',
'Jalen Brunson',
'Thomas Bryant',
'Reggie Bullock',
'Trey Burke',
'Alec Burks',
'Jimmy Butler',
'Devontae Cacok',
'Kentavious Caldwell-Pope',
'Facundo Campazzo',
'Vlatko Cancar',
'Clint Capela',
'Vernon Carey, Jr. ',
'Jevon Carter',
'Wendell Carter, Jr. ',
'Michael Carter-Williams',
'Alex Caruso',
'Willie Cauley-Stein',
'Chris Chiozza',
'Marquese Chriss',
'Gary Clark',
'Brandon Clarke',
'Jordan Clarkson',
'Nicolas Claxton',

'Amir Coffey',
'John Collins',
'Zach Collins',
'Mike Conley',
'Pat Connaughton',
'Quinn Cook',
'Tyler Cook',
'Robert Covington',
'Torrey Craig',
'Jae Crowder',
'Jarrett Culver',
'Seth Curry',
'Stephen Curry',
'Nate Darling',
'Anthony Davis',
'Ed Davis',
'Terence Davis',
'Matt Dellavedova',
'DeMar DeRozan',
'Mamadi Diakite',
'Hamidou Diallo',

'Gorgui Dieng',
'Spencer Dinwiddie',
'Donte DiVincenzo',
'Luka Doncic',
'Luguentz Dort',
'Damyean Dotson',
'Devon Dotson',
'Sekou Doumbouya',

'P.J. Dozier',
'Goran Dragic',
'Andre Drummond',
'Jared Dudley',
'Kris Dunn',
'Kevin Durant',
'Anthony Edwards',
'Carsen Edwards',
'C.J. Elleby',
'Wayne Ellington',
'Joel Embiid',
'James Ennis',
'Drew Eubanks',
'Dante Exum',
'Tacko Fall', 'Derrick Favors',
'Cristiano Felicio', 'Terrance Ferguson',
'Bruno Fernando',
'Dorian Finney-Smith',
'Malachi Flynn',
'Bryn Forbes',
'Trent Forrest',
'Evan Fournier',
'DeAaron Fox',
'Markelle Fultz',
'Wenyen Gabriel',
'Daniel Gafford',
'Danilo Gallinari',
'Langston Galloway',
'Darius Garland',
'Marc Gasol',
'Rudy Gay',
'Paul George',
'Taj Gibson',
'Harry Giles',
'Shai Gilgeous-Alexander',
'Anthony Gill',
'Rudy Gobert',
'Brandon Goodwin',
'Aaron Gordon',
'Eric Gordon',
'Devonte Graham',
'Jerami Grant',
'Danny Green',
'Draymond Green',
'JaMychal Green',
'Javonte Green',

'Jeff Green',
'Josh Green',

'Blake Griffin',
'Kyle Guy',
'Rui Hachimura',
'Tyrese Haliburton',
'Josh Hall',
'R.J. Hampton',
'Tim Hardaway Jr. ',
'James Harden',
'Maurice Harkless',

'Jared Harper',
'Montrezl Harrell',
'Gary Harris',
'Jalen Harris',
'Joe Harris',
'Tobias Harris',
'Josh Hart',
'Isaiah Hartenstein',

'Udonis Haslem',
'Jaxson Hayes',
'Killian Hayes',

'Gordon Hayward',
'Juancho Hernangomez',
'Willy Hernangomez',
'Tyler Herro',
'Buddy Hield',
'George Hill',
'Solomon Hill',
'Nate Hinton',
'Aaron Holiday',
'Jrue Holiday',
'Justin Holiday',
'Richaun Holmes',
'Rodney Hood',
'Al Horford',

'Talen Horton-Tucker',
'Danuel House',
'Dwight Howard',
'Markus Howard',
'Kevin Huerter',
'Elijah Hughes',
'DeAndre Hunter',
'Chandler Hutchison',
'Serge Ibaka',

'Andre Iguodala',
'Ersan Ilyasova',
'Joe Ingles',
'Brandon Ingram',
'Kyrie Irving',

'Jonathan Isaac',
'Wesley Iwundu',
'Frank Jackson',
'Josh Jackson',
'Jaren Jackson, Jr. ',
'Justin Jackson',
'Reggie Jackson',

'Justin James',
'LeBron James',
'DaQuan Jeffries',
'Ty Jerome',
'Isaiah Joe',
'Cameron Johnson',
'James Johnson',
'Keldon Johnson',
'Stanley Johnson',
'Tyler Johnson',
'Nikola Jokic',
'Derrick Jones',
'Tre Jones',
'Tyus Jones',
'DeAndre Jordan',
'Cory Joseph',
'Mfiondu Kabengele',
'Frank Kaminsky',
'Enes Kanter',

'Luke Kennard',
'Maxi Kleber',
'Nathan Knight',
'Kevin Knox',
'John Konchar',
'Furkan Korkmaz',
'Luke Kornet',
'Rodions Kurucs',
'Kyle Kuzma',
'Anthony Lamb',
'Jeremy Lamb',
'Romeo Langford',
'Zach LaVine',
'Jake Layman',
'Jalen Lecque',
'Damion Lee',
'Saben Lee',
'Alex Len',
'Kawhi Leonard',
'Meyers Leonard',
'Caris LeVert',
'Kira Lewis, Jr. ',
'Damian Lillard',
'Nassir Little',
'Kevon Looney',
'Brook Lopez',
'Robin Lopez',
'Kevin Love',
'Kyle Lowry',
'Timothe Luwawu-Cabarrot',
'Trey Lyles',

'Will Magnay',
'Theo Maledon',
'Karim Mane',
'Terance Mann',
'Nico Mannion',

'Boban Marjanovic',
'Lauri Markkanen',
'Naji Marshall',
'Caleb Martin',
'Cody Martin',
'K.J. Martin',
'Kelan Martin',
'Garrison Mathews',
'Wesley Matthews',
'Tyrese Maxey',
'Skylar Mays',
'Patrick McCaw',
'C.J. McCollum',
'T.J. McConnell',
'Jaden McDaniels',
'Jalen McDaniels',
'Doug McDermott',
'Sean McDermott',
'JaVale McGee',
'Rodney McGruder',
'Alfonzo McKinnie',
'Jordan McLaughlin',
'Ben McLemore',
'Nicolo Melli',
'DeAnthony Melton',
'Sam Merrill',
'Chimezie Metu',

'Khris Middleton',
'Darius Miller',
'Patty Mills',
'Paul Millsap',
'Shake Milton',
'Donovan Mitchell',
'Adam Mokoka',
'Malik Monk',
'ETwaun Moore',
'Ja Morant',
'Juwan Morgan',
'Marcus Morris',
'Markieff Morris',
'Monte Morris',

'Mychal Mulder',
'Dejounte Murray',
'Jamal Murray',
'Mike Muscala',
'Svi Mykhailiuk',
'Abdel Nader',

'Larry Nance, Jr. ',
'Aaron Nesmith',
'Raulzinho Neto',
'Georges Niang',
'Zeke Nnaji',
'Nerlens Noel',
'Jaylen Nowell',
'Frank Ntilikina',

'Kendrick Nunn',
'Jusuf Nurkic',
'David Nwaba',
'Jordan Nwora',

'Royce ONeale',
'Semi Ojeleye',
'Jahlil Okafor',
'Chuma Okeke',
'Josh Okogie',

'Onyeka Okongwu',
'Isaac Okoro',
'KZ Okpala',
'Victor Oladipo',
'Kelly Olynyk',
'Miye Oni',
'Cedi Osman',

'Daniel Oturu',
'Kelly Oubre, Jr. ',
'Jabari Parker',
'Eric Paschall',
'Patrick Patterson',
'Justin Patton',
'Chris Paul',
'Cameron Payne',
'Elfrid Payton',
'Reggie Perry',
'Theo Pinson',
'Mason Plumlee',
'Jakob Poeltl',
'Vincent Poirier',
'Aleksej Pokusevski',
'Jordan Poole',
'Jontay Porter',
'Kevin Porter, Jr. ',
'Michael Porter, Jr. ',
'Otto Porter',
'Bobby Portis',
'Kristaps Porzingis',
'Dwight Powell',
'Norman Powell',
'Taurean Prince',
'Payton Pritchard',
'Immanuel Quickley',
'Jahmius Ramsey',
'Chasson Randle',
'Julius Randle',
'Cam Reddish',
'J.J. Redick',
'Paul Reed, Jr. ',
'Naz Reid',
'Nick Richards',
'Josh Richardson',
'Grant Riller',
'Austin Rivers',
'Duncan Robinson',
'Jerome Robinson',
'Mitchell Robinson',
'Isaiah Roby',
'Rajon Rondo',
'Derrick Rose',
'Terrence Ross',
'Terry Rozier',
'Ricky Rubio',
'DAngelo Russell',
'Domantas Sabonis',

'Luka Samanic',
'JaKarr Sampson',
'Dario Saric',
'Tomas Satoransky',
'Dennis Schroder',
'Mike Scott',
'Jayden Scrubb',
'Collin Sexton',
'Landry Shamet',
'Pascal Siakam',
'Chris Silva',
'Ben Simmons',
'Anfernee Simons',
'Deividas Sirvydis',
'Alen Smailagic',
'Marcus Smart',
'Dennis Smith',
'Ish Smith',
'Jalen Smith',
'Tony Snell',
'Cassius Stanley',
'Lamar Stevens',
'Isaiah Stewart II',
'Max Strus',
'Edmond Sumner',
'Jaesean Tate',
'Jayson Tatum',
'Jeff Teague',
'Garrett Temple',
'Tyrell Terry',
'Daniel Theis',
'Brodric Thomas',
'Matt Thomas',
'Klay Thompson',
'Tristan Thompson',
'Matisse Thybulle',
'Killian Tillie',
'Xavier Tillman, Sr. ',
'Obi Toppin',
'Juan Toscano-Anderson',

'Axel Toupane',
'Karl-Anthony Towns',

'Gary Trent, Jr. ',
'P.J. Tucker',
'Rayjon Tucker',
'Myles Turner',
'Jonas Valanciunas',
'Denzel Valentine',
'Jarred Vanderbilt',
'Fred VanVleet',
'Devin Vassell',
'Gabe Vincent',

'Nikola Vucevic',

'Dean Wade',
'Moe Wagner',
'Kemba Walker',
'Lonnie Walker',
'John Wall',
'Brad Wanamaker',
'T.J. Warren',
'P.J. Washington',
'Yuta Watanabe',
'Tremont Waters',
'Paul Watson',
'Quinndary Weatherspoon',
'Russell Westbrook',
'Coby White',
'Derrick White',
'Hassan Whiteside',
'Greg Whittington',
'Andrew Wiggins',
'Grant Williams',
'Kenrich Williams',
'Lou Williams',
'Patrick Williams',
'Robert Williams',
'Zion Williamson',
'D.J. Wilson',
'Dylan Windler',
'Justise Winslow',
'Cassius Winston',
'James Wiseman',
'Christian Wood',
'Robert Woodard II',
'Delon Wright',
'Thaddeus Young',
'Trae Young',
'Cody Zeller',
'Ivica Zubac',



]
  if request.method == 'POST':
    player = request.form["search"]
    if player in player_list:
      player_list = [player]

  return render_template("webapp.html", display_list = player_list )


if __name__ == "__main__":
  app.run()
